### ISSUE TITLE
Allow Bearer tokens to be used

### ISSUE THREAD

**Issue by DieserMerlin** [mkody/twitch-emoticons#33]
Hello, I recognized you're using twurple for authentication, but only allow app authentication using ClientId and ClientSecret. Since the library used underneath is @twurple/api, why is there no option to use bearer authentication for increased rate limits?

Rate limits with user tokens are exponentially higher. This is the workaround I'm currently using to bypass this limitation but it is kinda hacky and dirty:

```typescript
const fetcher = new EmoteFetcher('', '');
const apiClient = getRefreshingApiClient(channelId);
Object.assign(fetcher, {apiClient});
...
```

This replaces the internally used API client with one that has automatically refreshing authentication provided by my application that's also using twurple. Adding another constructor allowing to pass either a custom auth provider or an api client directly would be a great improvement!

**Comment by mkody** [comment]
Hi! We've implemented the Twitch emotes with twurple with the idea that this should mostly be used as a server-side app and not require user login/tokens.

I'll look into adding a param for the case you want to bring your own auth provider 👍

**Comment by DieserMerlin** [comment]
My use case actually is server side but for multiple users. If I fetch for all of them but only use app credentials, I'll most likely hit my rate limit quite fast.

Thanks for looking into it 👌

**Comment by mkody** [comment]
Probably should have used a single object as a parameter for our constructor when I added our `clientId` and `clientSecret` the first time...

I've just [pushed a new version](https://github.com/mkody/twitch-emoticons/releases/tag/2.8.0) that accepts a third parameter: an object for options.  
And now there's a check in the `EmoteFetcher` constructor to see if an `apiClient` is set in it. If it's the case it'll use that one instead of creating our own.  
This should be more flexible than just checking for an `authProvider`, so you can reuse any existing `ApiClient` in a project.

An example I did to test:
```js
const authProvider = new StaticAuthProvider('<your client id>', '<your token>');
const apiClient = new ApiClient({ authProvider });

const fetcher = new EmoteFetcher(null, null, { apiClient });
```

Tell me how it goes!
